stages:
  - deploy
  - mirror

deploy:
  stage: deploy
  script:
    - aws s3 sync . s3://engineeringwithai --exclude ".git/*" --exclude ".gitlab-ci.yml" --exclude ".gitignore" --exclude "CLAUDE.md" --delete
    - aws cloudfront create-invalidation --distribution-id EPJSTCT5D6CBK --paths "/*"
  only:
    - main

mirror:
  stage: mirror
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  script:
    - git checkout -B main
    - git push --mirror git@github.com:engineering-with-ai/website.git
  only:
    - main
